version: '3'
services:
  app:
    container_name: example_app
    build:
      context: ./docker/app
      dockerfile: Dockerfile
    image: tiagodevweb/std-app:latest
    restart: always
    networks:
      - example
    volumes:
      - ./example:/var/www/html
    ports:
      - ${APP_PORT}:80
    working_dir: /var/www/html
  node:
    build:
      context: ./docker/node
      dockerfile: Dockerfile
    image: tiagodevweb/std-node:latest
    networks:
     - example
    volumes:
     - .:/opt
    working_dir: /opt
    command: echo hi
  db:
    container_name: example_db
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: homestead
      MYSQL_USER: homestead
      MYSQL_PASSWORD: secret
    ports:
      - ${DB_PORT}:3306
    networks:
      - example
    volumes:
      - dbdata:/var/lib/mysql
  cache:
    container_name: example_cache
    image: redis:alpine
    restart: always
    networks:
      - example
    volumes:
      - cachedata:/data
networks:
  example:
    driver: bridge
volumes:
  dbdata:
    driver: local
  cachedata:
    driver: local
